Repository hassio-addons/addon-bookstack, pull requests merged in 2021-02, with the labels that each got.

#41 :arrow_up: Upgrades composer to 2.0.9-r0
  bookstack/Dockerfile
Labels: dependencies

#44 ⬆ Update base image to 9.1.2
  bookstack/Dockerfile
  bookstack/build.json
Labels: dependencies

#45 ⬆ Update bookstack to v0.31.5
  bookstack/Dockerfile
Labels: dependencies, minor

#48 :arrow_up: Upgrades php7 to 7.4.15-r0
  bookstack/Dockerfile
Labels: dependencies

#53 ⬆ Update bookstack to v0.31.6
  bookstack/Dockerfile
Labels: dependencies

#54 ⬆ Add php-ldap
  bookstack/Dockerfile
Labels: dependencies

#55 🔨 Refactor nginx config with template
  bookstack/config.json
  bookstack/rootfs/etc/cont-init.d/nginx.sh
  bookstack/rootfs/etc/nginx/includes/resolver.conf
  bookstack/rootfs/etc/nginx/nginx.conf
  bookstack/rootfs/etc/nginx/servers/.gitkeep
  bookstack/rootfs/etc/nginx/servers/direct-ssl.disabled
  bookstack/rootfs/etc/nginx/servers/direct.disabled
  bookstack/rootfs/etc/nginx/templates/direct.gtpl
Labels: maintenance
