Repository hassio-addons/addon-bookstack, pull requests merged in 2021-11, with the labels that each got.

#155 🔨 Fix Laravel Logging
  bookstack/rootfs/etc/cont-init.d/bookstack.sh
  bookstack/rootfs/etc/services.d/php-fpm/run
Labels: bugfix

#156 ⬆️ Update Bookstack to v21.10.3
  bookstack/Dockerfile
Labels: dependencies

#157 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#163 ⬆️ Update base image and dependencies
  bookstack/Dockerfile
  bookstack/build.json
Labels: dependencies

#164 ⬆️ Update bookstack to v21.11.1
  bookstack/Dockerfile
Labels: dependencies
