Repository hassio-addons/addon-bookstack, pull requests merged in 2021-08, with the labels that each got.

#122 ⬆ Update php to 7.4.22-r0
  bookstack/Dockerfile
Labels: dependencies

#121 🔨 Add TLSv1.3
  bookstack/rootfs/etc/nginx/includes/ssl_params.conf
Labels: enhancement

#123 ⬆ Update Bookstack to v21.05.4
  bookstack/Dockerfile
Labels: dependencies

#125 ⬆️ Upgrades mariadb-client to 10.5.12-r0
  bookstack/Dockerfile
Labels: dependencies

#124 🚀 Add-on CI improvements
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/pr-labels.yaml
Labels: ci

#126 🚑 Fix contributing link in readme
  README.md
Labels: documentation

#127 🔑 Update NGINX SSL parameters
  bookstack/rootfs/etc/nginx/includes/ssl_params.conf
Labels: refactor
