Repository hassio-addons/addon-bookstack, pull requests merged in 2021-05, with the labels that each got.

#85 ⬆️ Upgrades add-on base image to v9.2.0
  bookstack/Dockerfile
  bookstack/build.json
Labels: dependencies

#86 Apply updated repository structure & CI workflow
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/pr-labels.yaml
Labels: ci

#87 Remove NGINX access log from Supervisor log ouput
  bookstack/rootfs/etc/nginx/nginx.conf
Labels: refactor

#88 ⬆️ Upgrades BookStack to v21.04.3
  bookstack/Dockerfile
Labels: dependencies

#89 🔨 Remove duplicated config item
  bookstack/config.json
  bookstack/rootfs/etc/services.d/php-fpm/run
Labels: breaking-change

#91 📚 Update docs for removal of APP_URL
  bookstack/DOCS.md
Labels: documentation

#94 ⬆️ Upgrades php7 to 7.4.19-r0
  bookstack/Dockerfile
Labels: dependencies

#100 ⬆️ Upgrades add-on base image to v9.2.1
  bookstack/Dockerfile
  bookstack/build.json
Labels: dependencies

#101 ⬆ Update bookstack to v21.05
  bookstack/Dockerfile
Labels: dependencies
