Repository hassio-addons/addon-bookstack, pull requests merged in 2021-04, with the labels that each got.

#71 ⬆️ Upgrades add-on base image to v9.1.7
  bookstack/Dockerfile
  bookstack/build.json
Labels: dependencies

#72 ⬆ Update Bookstack to v21.04
  bookstack/Dockerfile
Labels: dependencies

#76 Update nginx.sh to remove if Statement
  bookstack/rootfs/etc/cont-init.d/nginx.sh
Labels: enhancement

#78 ⬆ Update mariadb-client to 10.5.9
  bookstack/Dockerfile
Labels: dependencies

#77 💄 Fix line length for warning message
  bookstack/rootfs/etc/cont-init.d/nginx.sh
Labels: minor

#79 ⬆ Update bookstack to v21.04.1
  bookstack/Dockerfile
Labels: dependencies

#83 ⬆️ Upgrades composer to 2.0.13-r0
  bookstack/Dockerfile
Labels: dependencies
