Repository hassio-addons/addon-bookstack, pull requests merged in 2021-01, with the labels that each got.

#27 📚 Update year
  LICENSE.md
  README.md
  bookstack/.README.j2
  bookstack/DOCS.md
Labels: maintenance

#30 ⬆ Update image to 9.0.1 and package dependencies
  bookstack/Dockerfile
  bookstack/build.json
Labels: dependencies

#29 🔨 Remove no longer needed gitlab config
  .gitlab-ci.yml
Labels: maintenance

#28 📚 Update Code of Conduct
  CODE_OF_CONDUCT.md
Labels: maintenance

#31 📚 Documentation updates
  README.md
  bookstack/DOCS.md
Labels: documentation

#33 Fix add-on description extraction
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
Labels: ci

#34 📚 Fix commit activity
  README.md
Labels: documentation

#32 ✨ Add envvars option to configuration
  bookstack/DOCS.md
  bookstack/config.json
  bookstack/rootfs/etc/services.d/php-fpm/run
Labels: new-feature

#37 🔨 Update build args
  bookstack/Dockerfile
Labels: ci
