Repository hassio-addons/addon-bookstack, pull requests merged in 2021-03, with the labels that each got.

#59 :arrow_up: Upgrades composer to 2.0.11-r0
  bookstack/Dockerfile
Labels: dependencies

#60 :arrow_up: Upgrades add-on base image to v9.1.5
  bookstack/Dockerfile
  bookstack/build.json
Labels: dependencies

#61 ⬆ Update bookstack to v0.31.7
  bookstack/Dockerfile
Labels: dependencies

#64 🔨 Remove cache rules
  bookstack/rootfs/etc/nginx/includes/server_params.conf
Labels: refactor

#65 ⬆ Update Bookstack to v0.31.8
  bookstack/Dockerfile
Labels: dependencies

#66 📚 Fix image link on edge repo
  bookstack/.README.j2
Labels: documentation
