Repository hassio-addons/addon-bookstack, pull requests merged in 2022-05, with the labels that each got.

#178 ⬆️ Update image, PHP and dependencies
  bookstack/Dockerfile
  bookstack/build.json
  bookstack/rootfs/etc/cont-init.d/bookstack.sh
  bookstack/rootfs/etc/php8/php-fpm.d/www.conf
  bookstack/rootfs/etc/services.d/php-fpm/run
Labels: dependencies

#179 🚑 Add php-xmlwriter for QR Code generation
  bookstack/Dockerfile
Labels: dependencies, bugfix

#180 ⬆️ Update Bookstack to v22.04.1
  bookstack/Dockerfile
Labels: dependencies

#181 :lock: Sign add-on with Codenotary Community Attestation Service (CAS)
  .github/workflows/deploy.yaml
  bookstack/build.json
  bookstack/build.yaml
  bookstack/config.json
  bookstack/config.yaml
Labels: enhancement
